#!/usr/bin/env bash
set -euf
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXE="${DIR}/../javascript/node_modules/.bin/cucumber-html-formatter"

${EXE}
#docker run --interactive --rm cucumber/html-formatter:4.0.0 --format ndjson
