# Builds a docker image used for building most projects in this repo. It's
# used both by contributors and CI.
#
# Extend alpine-node, because alpine doesn't have node 8 yet, and we need
# it to build certain packages
FROM golang:1.10.0-alpine3.7

WORKDIR /go/src/github.com/cucumber/cucumber

RUN apk add --no-cache --update --upgrade git make
RUN go get github.com/stretchr/testify
