// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gherkin.proto

package io_cucumber_messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GherkinDocument struct {
	Uri                  string     `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Feature              *Feature   `protobuf:"bytes,2,opt,name=feature,proto3" json:"feature,omitempty"`
	Comments             []*Comment `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GherkinDocument) Reset()         { *m = GherkinDocument{} }
func (m *GherkinDocument) String() string { return proto.CompactTextString(m) }
func (*GherkinDocument) ProtoMessage()    {}
func (*GherkinDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{0}
}
func (m *GherkinDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GherkinDocument.Unmarshal(m, b)
}
func (m *GherkinDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GherkinDocument.Marshal(b, m, deterministic)
}
func (dst *GherkinDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GherkinDocument.Merge(dst, src)
}
func (m *GherkinDocument) XXX_Size() int {
	return xxx_messageInfo_GherkinDocument.Size(m)
}
func (m *GherkinDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_GherkinDocument.DiscardUnknown(m)
}

var xxx_messageInfo_GherkinDocument proto.InternalMessageInfo

func (m *GherkinDocument) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *GherkinDocument) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

func (m *GherkinDocument) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type Feature struct {
	Location             *Location       `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Tags                 []*Tag          `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Language             string          `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Keyword              string          `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name                 string          `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description          string          `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Children             []*FeatureChild `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{1}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Feature) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Feature) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Feature) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Feature) GetChildren() []*FeatureChild {
	if m != nil {
		return m.Children
	}
	return nil
}

type FeatureChild struct {
	// Types that are valid to be assigned to Value:
	//	*FeatureChild_Rule
	//	*FeatureChild_Background
	//	*FeatureChild_Scenario
	Value                isFeatureChild_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FeatureChild) Reset()         { *m = FeatureChild{} }
func (m *FeatureChild) String() string { return proto.CompactTextString(m) }
func (*FeatureChild) ProtoMessage()    {}
func (*FeatureChild) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{2}
}
func (m *FeatureChild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureChild.Unmarshal(m, b)
}
func (m *FeatureChild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureChild.Marshal(b, m, deterministic)
}
func (dst *FeatureChild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureChild.Merge(dst, src)
}
func (m *FeatureChild) XXX_Size() int {
	return xxx_messageInfo_FeatureChild.Size(m)
}
func (m *FeatureChild) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureChild.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureChild proto.InternalMessageInfo

type isFeatureChild_Value interface {
	isFeatureChild_Value()
}

type FeatureChild_Rule struct {
	Rule *Rule `protobuf:"bytes,1,opt,name=rule,proto3,oneof"`
}
type FeatureChild_Background struct {
	Background *Background `protobuf:"bytes,2,opt,name=background,proto3,oneof"`
}
type FeatureChild_Scenario struct {
	Scenario *Scenario `protobuf:"bytes,3,opt,name=scenario,proto3,oneof"`
}

func (*FeatureChild_Rule) isFeatureChild_Value()       {}
func (*FeatureChild_Background) isFeatureChild_Value() {}
func (*FeatureChild_Scenario) isFeatureChild_Value()   {}

func (m *FeatureChild) GetValue() isFeatureChild_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *FeatureChild) GetRule() *Rule {
	if x, ok := m.GetValue().(*FeatureChild_Rule); ok {
		return x.Rule
	}
	return nil
}

func (m *FeatureChild) GetBackground() *Background {
	if x, ok := m.GetValue().(*FeatureChild_Background); ok {
		return x.Background
	}
	return nil
}

func (m *FeatureChild) GetScenario() *Scenario {
	if x, ok := m.GetValue().(*FeatureChild_Scenario); ok {
		return x.Scenario
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FeatureChild) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FeatureChild_OneofMarshaler, _FeatureChild_OneofUnmarshaler, _FeatureChild_OneofSizer, []interface{}{
		(*FeatureChild_Rule)(nil),
		(*FeatureChild_Background)(nil),
		(*FeatureChild_Scenario)(nil),
	}
}

func _FeatureChild_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FeatureChild)
	// value
	switch x := m.Value.(type) {
	case *FeatureChild_Rule:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Rule); err != nil {
			return err
		}
	case *FeatureChild_Background:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Background); err != nil {
			return err
		}
	case *FeatureChild_Scenario:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Scenario); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FeatureChild.Value has unexpected type %T", x)
	}
	return nil
}

func _FeatureChild_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FeatureChild)
	switch tag {
	case 1: // value.rule
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Rule)
		err := b.DecodeMessage(msg)
		m.Value = &FeatureChild_Rule{msg}
		return true, err
	case 2: // value.background
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Background)
		err := b.DecodeMessage(msg)
		m.Value = &FeatureChild_Background{msg}
		return true, err
	case 3: // value.scenario
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Scenario)
		err := b.DecodeMessage(msg)
		m.Value = &FeatureChild_Scenario{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FeatureChild_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FeatureChild)
	// value
	switch x := m.Value.(type) {
	case *FeatureChild_Rule:
		s := proto.Size(x.Rule)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *FeatureChild_Background:
		s := proto.Size(x.Background)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *FeatureChild_Scenario:
		s := proto.Size(x.Scenario)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Rule struct {
	Location             *Location    `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Keyword              string       `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name                 string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Children             []*RuleChild `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{3}
}
func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (dst *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(dst, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Rule) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *Rule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rule) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Rule) GetChildren() []*RuleChild {
	if m != nil {
		return m.Children
	}
	return nil
}

type RuleChild struct {
	// Types that are valid to be assigned to Value:
	//	*RuleChild_Background
	//	*RuleChild_Scenario
	Value                isRuleChild_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RuleChild) Reset()         { *m = RuleChild{} }
func (m *RuleChild) String() string { return proto.CompactTextString(m) }
func (*RuleChild) ProtoMessage()    {}
func (*RuleChild) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{4}
}
func (m *RuleChild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleChild.Unmarshal(m, b)
}
func (m *RuleChild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleChild.Marshal(b, m, deterministic)
}
func (dst *RuleChild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleChild.Merge(dst, src)
}
func (m *RuleChild) XXX_Size() int {
	return xxx_messageInfo_RuleChild.Size(m)
}
func (m *RuleChild) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleChild.DiscardUnknown(m)
}

var xxx_messageInfo_RuleChild proto.InternalMessageInfo

type isRuleChild_Value interface {
	isRuleChild_Value()
}

type RuleChild_Background struct {
	Background *Background `protobuf:"bytes,1,opt,name=background,proto3,oneof"`
}
type RuleChild_Scenario struct {
	Scenario *Scenario `protobuf:"bytes,2,opt,name=scenario,proto3,oneof"`
}

func (*RuleChild_Background) isRuleChild_Value() {}
func (*RuleChild_Scenario) isRuleChild_Value()   {}

func (m *RuleChild) GetValue() isRuleChild_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RuleChild) GetBackground() *Background {
	if x, ok := m.GetValue().(*RuleChild_Background); ok {
		return x.Background
	}
	return nil
}

func (m *RuleChild) GetScenario() *Scenario {
	if x, ok := m.GetValue().(*RuleChild_Scenario); ok {
		return x.Scenario
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RuleChild) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RuleChild_OneofMarshaler, _RuleChild_OneofUnmarshaler, _RuleChild_OneofSizer, []interface{}{
		(*RuleChild_Background)(nil),
		(*RuleChild_Scenario)(nil),
	}
}

func _RuleChild_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RuleChild)
	// value
	switch x := m.Value.(type) {
	case *RuleChild_Background:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Background); err != nil {
			return err
		}
	case *RuleChild_Scenario:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Scenario); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RuleChild.Value has unexpected type %T", x)
	}
	return nil
}

func _RuleChild_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RuleChild)
	switch tag {
	case 1: // value.background
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Background)
		err := b.DecodeMessage(msg)
		m.Value = &RuleChild_Background{msg}
		return true, err
	case 2: // value.scenario
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Scenario)
		err := b.DecodeMessage(msg)
		m.Value = &RuleChild_Scenario{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RuleChild_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RuleChild)
	// value
	switch x := m.Value.(type) {
	case *RuleChild_Background:
		s := proto.Size(x.Background)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RuleChild_Scenario:
		s := proto.Size(x.Scenario)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Background struct {
	Location             *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Keyword              string    `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Steps                []*Step   `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Background) Reset()         { *m = Background{} }
func (m *Background) String() string { return proto.CompactTextString(m) }
func (*Background) ProtoMessage()    {}
func (*Background) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{5}
}
func (m *Background) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Background.Unmarshal(m, b)
}
func (m *Background) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Background.Marshal(b, m, deterministic)
}
func (dst *Background) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Background.Merge(dst, src)
}
func (m *Background) XXX_Size() int {
	return xxx_messageInfo_Background.Size(m)
}
func (m *Background) XXX_DiscardUnknown() {
	xxx_messageInfo_Background.DiscardUnknown(m)
}

var xxx_messageInfo_Background proto.InternalMessageInfo

func (m *Background) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Background) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *Background) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Background) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Background) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

type Scenario struct {
	Location             *Location   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Tags                 []*Tag      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Keyword              string      `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name                 string      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Steps                []*Step     `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	Examples             []*Examples `protobuf:"bytes,7,rep,name=examples,proto3" json:"examples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Scenario) Reset()         { *m = Scenario{} }
func (m *Scenario) String() string { return proto.CompactTextString(m) }
func (*Scenario) ProtoMessage()    {}
func (*Scenario) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{6}
}
func (m *Scenario) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scenario.Unmarshal(m, b)
}
func (m *Scenario) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scenario.Marshal(b, m, deterministic)
}
func (dst *Scenario) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scenario.Merge(dst, src)
}
func (m *Scenario) XXX_Size() int {
	return xxx_messageInfo_Scenario.Size(m)
}
func (m *Scenario) XXX_DiscardUnknown() {
	xxx_messageInfo_Scenario.DiscardUnknown(m)
}

var xxx_messageInfo_Scenario proto.InternalMessageInfo

func (m *Scenario) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Scenario) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Scenario) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *Scenario) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Scenario) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Scenario) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Scenario) GetExamples() []*Examples {
	if m != nil {
		return m.Examples
	}
	return nil
}

type Comment struct {
	Location             *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Text                 string    `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{7}
}
func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (dst *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(dst, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Comment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type DataTable struct {
	Location             *Location   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Rows                 []*TableRow `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DataTable) Reset()         { *m = DataTable{} }
func (m *DataTable) String() string { return proto.CompactTextString(m) }
func (*DataTable) ProtoMessage()    {}
func (*DataTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{8}
}
func (m *DataTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTable.Unmarshal(m, b)
}
func (m *DataTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTable.Marshal(b, m, deterministic)
}
func (dst *DataTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTable.Merge(dst, src)
}
func (m *DataTable) XXX_Size() int {
	return xxx_messageInfo_DataTable.Size(m)
}
func (m *DataTable) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTable.DiscardUnknown(m)
}

var xxx_messageInfo_DataTable proto.InternalMessageInfo

func (m *DataTable) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *DataTable) GetRows() []*TableRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type DocString struct {
	Location             *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	ContentType          string    `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content              string    `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Delimiter            string    `protobuf:"bytes,4,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DocString) Reset()         { *m = DocString{} }
func (m *DocString) String() string { return proto.CompactTextString(m) }
func (*DocString) ProtoMessage()    {}
func (*DocString) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{9}
}
func (m *DocString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocString.Unmarshal(m, b)
}
func (m *DocString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocString.Marshal(b, m, deterministic)
}
func (dst *DocString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocString.Merge(dst, src)
}
func (m *DocString) XXX_Size() int {
	return xxx_messageInfo_DocString.Size(m)
}
func (m *DocString) XXX_DiscardUnknown() {
	xxx_messageInfo_DocString.DiscardUnknown(m)
}

var xxx_messageInfo_DocString proto.InternalMessageInfo

func (m *DocString) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *DocString) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *DocString) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *DocString) GetDelimiter() string {
	if m != nil {
		return m.Delimiter
	}
	return ""
}

type Examples struct {
	Location             *Location   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Tags                 []*Tag      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Keyword              string      `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Name                 string      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	TableHeader          *TableRow   `protobuf:"bytes,6,opt,name=table_header,json=tableHeader,proto3" json:"table_header,omitempty"`
	TableBody            []*TableRow `protobuf:"bytes,7,rep,name=table_body,json=tableBody,proto3" json:"table_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Examples) Reset()         { *m = Examples{} }
func (m *Examples) String() string { return proto.CompactTextString(m) }
func (*Examples) ProtoMessage()    {}
func (*Examples) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{10}
}
func (m *Examples) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Examples.Unmarshal(m, b)
}
func (m *Examples) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Examples.Marshal(b, m, deterministic)
}
func (dst *Examples) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Examples.Merge(dst, src)
}
func (m *Examples) XXX_Size() int {
	return xxx_messageInfo_Examples.Size(m)
}
func (m *Examples) XXX_DiscardUnknown() {
	xxx_messageInfo_Examples.DiscardUnknown(m)
}

var xxx_messageInfo_Examples proto.InternalMessageInfo

func (m *Examples) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Examples) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Examples) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *Examples) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Examples) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Examples) GetTableHeader() *TableRow {
	if m != nil {
		return m.TableHeader
	}
	return nil
}

func (m *Examples) GetTableBody() []*TableRow {
	if m != nil {
		return m.TableBody
	}
	return nil
}

type Step struct {
	Location *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Keyword  string    `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Text     string    `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// Types that are valid to be assigned to Argument:
	//	*Step_DocString
	//	*Step_DataTable
	Argument             isStep_Argument `protobuf_oneof:"argument"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{11}
}
func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (dst *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(dst, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

type isStep_Argument interface {
	isStep_Argument()
}

type Step_DocString struct {
	DocString *DocString `protobuf:"bytes,5,opt,name=doc_string,json=docString,proto3,oneof"`
}
type Step_DataTable struct {
	DataTable *DataTable `protobuf:"bytes,6,opt,name=data_table,json=dataTable,proto3,oneof"`
}

func (*Step_DocString) isStep_Argument() {}
func (*Step_DataTable) isStep_Argument() {}

func (m *Step) GetArgument() isStep_Argument {
	if m != nil {
		return m.Argument
	}
	return nil
}

func (m *Step) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Step) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *Step) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Step) GetDocString() *DocString {
	if x, ok := m.GetArgument().(*Step_DocString); ok {
		return x.DocString
	}
	return nil
}

func (m *Step) GetDataTable() *DataTable {
	if x, ok := m.GetArgument().(*Step_DataTable); ok {
		return x.DataTable
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Step) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Step_OneofMarshaler, _Step_OneofUnmarshaler, _Step_OneofSizer, []interface{}{
		(*Step_DocString)(nil),
		(*Step_DataTable)(nil),
	}
}

func _Step_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Step)
	// argument
	switch x := m.Argument.(type) {
	case *Step_DocString:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DocString); err != nil {
			return err
		}
	case *Step_DataTable:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DataTable); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Step.Argument has unexpected type %T", x)
	}
	return nil
}

func _Step_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Step)
	switch tag {
	case 5: // argument.doc_string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DocString)
		err := b.DecodeMessage(msg)
		m.Argument = &Step_DocString{msg}
		return true, err
	case 6: // argument.data_table
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DataTable)
		err := b.DecodeMessage(msg)
		m.Argument = &Step_DataTable{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Step_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Step)
	// argument
	switch x := m.Argument.(type) {
	case *Step_DocString:
		s := proto.Size(x.DocString)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Step_DataTable:
		s := proto.Size(x.DataTable)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type TableCell struct {
	Location             *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Value                string    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TableCell) Reset()         { *m = TableCell{} }
func (m *TableCell) String() string { return proto.CompactTextString(m) }
func (*TableCell) ProtoMessage()    {}
func (*TableCell) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{12}
}
func (m *TableCell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableCell.Unmarshal(m, b)
}
func (m *TableCell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableCell.Marshal(b, m, deterministic)
}
func (dst *TableCell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableCell.Merge(dst, src)
}
func (m *TableCell) XXX_Size() int {
	return xxx_messageInfo_TableCell.Size(m)
}
func (m *TableCell) XXX_DiscardUnknown() {
	xxx_messageInfo_TableCell.DiscardUnknown(m)
}

var xxx_messageInfo_TableCell proto.InternalMessageInfo

func (m *TableCell) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *TableCell) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TableRow struct {
	Location             *Location    `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Cells                []*TableCell `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TableRow) Reset()         { *m = TableRow{} }
func (m *TableRow) String() string { return proto.CompactTextString(m) }
func (*TableRow) ProtoMessage()    {}
func (*TableRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{13}
}
func (m *TableRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableRow.Unmarshal(m, b)
}
func (m *TableRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableRow.Marshal(b, m, deterministic)
}
func (dst *TableRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableRow.Merge(dst, src)
}
func (m *TableRow) XXX_Size() int {
	return xxx_messageInfo_TableRow.Size(m)
}
func (m *TableRow) XXX_DiscardUnknown() {
	xxx_messageInfo_TableRow.DiscardUnknown(m)
}

var xxx_messageInfo_TableRow proto.InternalMessageInfo

func (m *TableRow) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *TableRow) GetCells() []*TableCell {
	if m != nil {
		return m.Cells
	}
	return nil
}

type Tag struct {
	Location             *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_gherkin_6d1a3d8a6ee2d8ad, []int{14}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GherkinDocument)(nil), "io.cucumber.messages.GherkinDocument")
	proto.RegisterType((*Feature)(nil), "io.cucumber.messages.Feature")
	proto.RegisterType((*FeatureChild)(nil), "io.cucumber.messages.FeatureChild")
	proto.RegisterType((*Rule)(nil), "io.cucumber.messages.Rule")
	proto.RegisterType((*RuleChild)(nil), "io.cucumber.messages.RuleChild")
	proto.RegisterType((*Background)(nil), "io.cucumber.messages.Background")
	proto.RegisterType((*Scenario)(nil), "io.cucumber.messages.Scenario")
	proto.RegisterType((*Comment)(nil), "io.cucumber.messages.Comment")
	proto.RegisterType((*DataTable)(nil), "io.cucumber.messages.DataTable")
	proto.RegisterType((*DocString)(nil), "io.cucumber.messages.DocString")
	proto.RegisterType((*Examples)(nil), "io.cucumber.messages.Examples")
	proto.RegisterType((*Step)(nil), "io.cucumber.messages.Step")
	proto.RegisterType((*TableCell)(nil), "io.cucumber.messages.TableCell")
	proto.RegisterType((*TableRow)(nil), "io.cucumber.messages.TableRow")
	proto.RegisterType((*Tag)(nil), "io.cucumber.messages.Tag")
}

func init() { proto.RegisterFile("gherkin.proto", fileDescriptor_gherkin_6d1a3d8a6ee2d8ad) }

var fileDescriptor_gherkin_6d1a3d8a6ee2d8ad = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x15, 0x1f, 0xb2, 0xc8, 0x2b, 0x1b, 0x6d, 0x07, 0x5e, 0xb0, 0x46, 0x6b, 0xab, 0x5c, 0x79,
	0x53, 0xc1, 0x70, 0x51, 0x14, 0x7d, 0xa2, 0x95, 0xdc, 0x56, 0x8b, 0x76, 0x33, 0x56, 0x17, 0x5d,
	0x04, 0xc2, 0x88, 0xbc, 0xa1, 0x09, 0x53, 0x1c, 0x61, 0x38, 0x8c, 0x2d, 0x04, 0x01, 0xf2, 0x15,
	0xc9, 0x36, 0xc8, 0x2f, 0xe4, 0x23, 0x02, 0x24, 0x8b, 0xfc, 0x47, 0xbe, 0x22, 0xe0, 0x68, 0x48,
	0x09, 0x8e, 0xa8, 0x04, 0x21, 0x12, 0x24, 0x3b, 0xce, 0xf0, 0x9c, 0xcb, 0xb9, 0xe7, 0x9c, 0x99,
	0x21, 0xec, 0x45, 0x17, 0x28, 0x2e, 0xe3, 0xb4, 0x3f, 0x17, 0x5c, 0x72, 0xb2, 0x1f, 0xf3, 0x7e,
	0x90, 0x07, 0xf9, 0x6c, 0x8a, 0xa2, 0x3f, 0xc3, 0x2c, 0x63, 0x11, 0x66, 0x07, 0x7b, 0x19, 0xcf,
	0x45, 0x80, 0xd9, 0x12, 0xe4, 0x3f, 0x34, 0xe0, 0xb3, 0xbf, 0x97, 0xb4, 0x33, 0x1e, 0xe4, 0x33,
	0x4c, 0x25, 0xf9, 0x1c, 0xac, 0x5c, 0xc4, 0x9e, 0xd1, 0x33, 0x8e, 0x5d, 0x5a, 0x3c, 0x92, 0x1f,
	0xa0, 0x73, 0x1b, 0x99, 0xcc, 0x05, 0x7a, 0x66, 0xcf, 0x38, 0xee, 0x9e, 0x7e, 0xdd, 0xdf, 0x54,
	0xbc, 0xff, 0xd7, 0x12, 0x44, 0x4b, 0x34, 0xf9, 0x11, 0x9c, 0x80, 0xcf, 0x8a, 0xaa, 0x99, 0x67,
	0xf5, 0xac, 0x7a, 0xe6, 0x70, 0x89, 0xa2, 0x15, 0xdc, 0x7f, 0x64, 0x42, 0x47, 0xd7, 0x23, 0x3f,
	0x81, 0x93, 0xf0, 0x80, 0xc9, 0x98, 0xa7, 0x6a, 0x59, 0xdd, 0xd3, 0xc3, 0xcd, 0x65, 0xfe, 0xd1,
	0x28, 0x5a, 0xe1, 0xc9, 0xb7, 0x60, 0x4b, 0x16, 0x65, 0x9e, 0xa9, 0x3e, 0xff, 0xe5, 0x66, 0xde,
	0x98, 0x45, 0x54, 0xc1, 0xc8, 0x01, 0x38, 0x09, 0x4b, 0xa3, 0x9c, 0x45, 0xe8, 0x59, 0x4a, 0x81,
	0x6a, 0x4c, 0x3c, 0xe8, 0x5c, 0xe2, 0xe2, 0x8a, 0x8b, 0xd0, 0xb3, 0xd5, 0xab, 0x72, 0x48, 0x08,
	0xd8, 0x29, 0x9b, 0xa1, 0xd7, 0x56, 0xd3, 0xea, 0x99, 0xf4, 0xa0, 0x1b, 0x62, 0x16, 0x88, 0x78,
	0xae, 0xd6, 0xbd, 0xa3, 0x5e, 0xad, 0x4f, 0x91, 0xdf, 0xc0, 0x09, 0x2e, 0xe2, 0x24, 0x14, 0x98,
	0x7a, 0x1d, 0xb5, 0x3c, 0x7f, 0xab, 0xae, 0xc3, 0x02, 0x4c, 0x2b, 0x8e, 0xff, 0xdc, 0x80, 0xdd,
	0xf5, 0x57, 0xe4, 0x04, 0x6c, 0x91, 0x27, 0xa8, 0x35, 0x3a, 0xd8, 0x5c, 0x8c, 0xe6, 0x09, 0x8e,
	0x5a, 0x54, 0x21, 0xc9, 0x00, 0x60, 0xca, 0x82, 0xcb, 0x48, 0xf0, 0x3c, 0x0d, 0xb5, 0xb9, 0xbd,
	0xcd, 0xbc, 0x41, 0x85, 0x1b, 0xb5, 0xe8, 0x1a, 0x8b, 0xfc, 0x02, 0x4e, 0x16, 0x60, 0xca, 0x44,
	0xcc, 0x95, 0x64, 0xb5, 0xee, 0x9c, 0x6b, 0xd4, 0xa8, 0x45, 0x2b, 0xc6, 0xa0, 0x03, 0xed, 0x3b,
	0x2c, 0xc9, 0xd1, 0x7f, 0x61, 0x80, 0x5d, 0xac, 0xad, 0x91, 0xdb, 0x6b, 0x16, 0x99, 0x9b, 0x2d,
	0xb2, 0xea, 0x2d, 0xb2, 0x5f, 0xb7, 0xe8, 0xe7, 0x35, 0x8b, 0xda, 0xca, 0xa2, 0xa3, 0x7a, 0x55,
	0x6f, 0xfa, 0xf3, 0xc0, 0x00, 0xb7, 0x9a, 0xbf, 0x21, 0xb5, 0xd1, 0x58, 0x6a, 0xf3, 0xdd, 0xa5,
	0x7e, 0x66, 0x00, 0xac, 0xbe, 0xf1, 0x51, 0x09, 0x7e, 0x02, 0xed, 0x4c, 0xe2, 0x3c, 0xd3, 0x6a,
	0xd7, 0x64, 0xf8, 0x5c, 0xe2, 0x9c, 0x2e, 0x81, 0xfe, 0x13, 0x13, 0x9c, 0xb2, 0xdd, 0x0f, 0x79,
	0x52, 0xac, 0x75, 0x6e, 0x6d, 0xee, 0xdc, 0xae, 0xef, 0xbc, 0xbd, 0xa5, 0xf3, 0x9d, 0xb7, 0xec,
	0xbc, 0x68, 0x16, 0xaf, 0xd9, 0x6c, 0x9e, 0x60, 0xa6, 0xcf, 0x8f, 0x9a, 0x66, 0xff, 0xd4, 0x28,
	0x5a, 0xe1, 0xfd, 0xff, 0xa1, 0xa3, 0xcf, 0xdc, 0x46, 0x9a, 0x11, 0xb0, 0x25, 0x5e, 0x4b, 0xed,
	0xbd, 0x7a, 0xf6, 0xef, 0x82, 0x7b, 0xc6, 0x24, 0x1b, 0xb3, 0x69, 0xc3, 0xcd, 0x7c, 0x0a, 0xb6,
	0xe0, 0x57, 0xa5, 0x21, 0x87, 0x75, 0x86, 0x4c, 0x13, 0xa4, 0xfc, 0x8a, 0x2a, 0xac, 0xff, 0xd8,
	0x00, 0xf7, 0x8c, 0x07, 0xe7, 0x52, 0xc4, 0x69, 0xd4, 0xe8, 0xeb, 0xdf, 0xc0, 0x6e, 0xc0, 0x53,
	0x89, 0xa9, 0x9c, 0xc8, 0xc5, 0x1c, 0x75, 0x8b, 0x5d, 0x3d, 0x37, 0x5e, 0xcc, 0xd5, 0x85, 0xa0,
	0x87, 0x65, 0x04, 0xf4, 0x90, 0x7c, 0x05, 0x6e, 0x88, 0x49, 0x3c, 0x8b, 0x25, 0x0a, 0x9d, 0x83,
	0xd5, 0x84, 0xff, 0xd4, 0x04, 0xa7, 0xf4, 0xe4, 0x53, 0x8e, 0xec, 0x1f, 0xb0, 0x2b, 0x0b, 0xf9,
	0x27, 0x17, 0xc8, 0x42, 0x14, 0xea, 0x8e, 0x7b, 0xb3, 0x51, 0x5d, 0xc5, 0x19, 0x29, 0x0a, 0xf9,
	0x15, 0x60, 0x59, 0x62, 0xca, 0xc3, 0xc5, 0xf6, 0x14, 0x57, 0x05, 0x5c, 0xc5, 0x18, 0xf0, 0x70,
	0xe1, 0xdf, 0x37, 0xc1, 0x2e, 0xb6, 0xc4, 0xfb, 0x3b, 0xc3, 0x54, 0xbc, 0xad, 0x55, 0xbc, 0xc9,
	0xef, 0x00, 0x21, 0x0f, 0x26, 0x99, 0x4a, 0x98, 0x52, 0xa5, 0xf6, 0x52, 0xa8, 0x82, 0x38, 0x6a,
	0x51, 0x37, 0xac, 0x52, 0x59, 0x54, 0x60, 0x92, 0x4d, 0x54, 0x1b, 0x5a, 0xb4, 0xba, 0x0a, 0xe5,
	0x46, 0x52, 0x15, 0xca, 0xc1, 0x00, 0xc0, 0x61, 0x22, 0x52, 0xbf, 0x6b, 0xfe, 0x2d, 0x70, 0xd5,
	0xe4, 0x10, 0x93, 0xa4, 0x91, 0x0c, 0xfb, 0xfa, 0x7a, 0xd0, 0x22, 0xe8, 0xbb, 0xe2, 0x1e, 0x38,
	0xa5, 0xf0, 0x8d, 0xaa, 0x7f, 0x0f, 0xed, 0x00, 0x93, 0xa4, 0xcc, 0xea, 0xd1, 0x16, 0x8f, 0x8b,
	0x4e, 0xe8, 0x12, 0xed, 0xff, 0x07, 0xd6, 0x98, 0x45, 0x4d, 0xcf, 0x28, 0x95, 0x6d, 0x73, 0x95,
	0xed, 0xc1, 0xfe, 0x4b, 0xf3, 0x8b, 0x61, 0x49, 0xfe, 0x57, 0x93, 0xa7, 0x3b, 0xea, 0xa7, 0xf8,
	0xbb, 0x57, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xe6, 0x10, 0x5a, 0x4a, 0x0b, 0x00, 0x00,
}
