// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sources.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Location struct {
	Line                 uint32   `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Column               uint32   `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_sources_dbd726974e7b6608, []int{0}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLine() uint32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *Location) GetColumn() uint32 {
	if m != nil {
		return m.Column
	}
	return 0
}

type Attachment struct {
	Source               *SourceReference `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Data                 string           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Media                *Media           `protobuf:"bytes,3,opt,name=media,proto3" json:"media,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Attachment) Reset()         { *m = Attachment{} }
func (m *Attachment) String() string { return proto.CompactTextString(m) }
func (*Attachment) ProtoMessage()    {}
func (*Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_sources_dbd726974e7b6608, []int{1}
}
func (m *Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attachment.Unmarshal(m, b)
}
func (m *Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attachment.Marshal(b, m, deterministic)
}
func (dst *Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attachment.Merge(dst, src)
}
func (m *Attachment) XXX_Size() int {
	return xxx_messageInfo_Attachment.Size(m)
}
func (m *Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_Attachment proto.InternalMessageInfo

func (m *Attachment) GetSource() *SourceReference {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Attachment) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Attachment) GetMedia() *Media {
	if m != nil {
		return m.Media
	}
	return nil
}

type Media struct {
	Encoding             string   `protobuf:"bytes,1,opt,name=encoding,proto3" json:"encoding,omitempty"`
	ContentType          string   `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_sources_dbd726974e7b6608, []int{2}
}
func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (dst *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(dst, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

func (m *Media) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *Media) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type Source struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Media                *Media   `protobuf:"bytes,3,opt,name=media,proto3" json:"media,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_sources_dbd726974e7b6608, []int{3}
}
func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (dst *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(dst, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Source) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Source) GetMedia() *Media {
	if m != nil {
		return m.Media
	}
	return nil
}

type SourceReference struct {
	Uri                  string    `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Location             *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SourceReference) Reset()         { *m = SourceReference{} }
func (m *SourceReference) String() string { return proto.CompactTextString(m) }
func (*SourceReference) ProtoMessage()    {}
func (*SourceReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_sources_dbd726974e7b6608, []int{4}
}
func (m *SourceReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceReference.Unmarshal(m, b)
}
func (m *SourceReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceReference.Marshal(b, m, deterministic)
}
func (dst *SourceReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceReference.Merge(dst, src)
}
func (m *SourceReference) XXX_Size() int {
	return xxx_messageInfo_SourceReference.Size(m)
}
func (m *SourceReference) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceReference.DiscardUnknown(m)
}

var xxx_messageInfo_SourceReference proto.InternalMessageInfo

func (m *SourceReference) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *SourceReference) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "io.cucumber.messages.Location")
	proto.RegisterType((*Attachment)(nil), "io.cucumber.messages.Attachment")
	proto.RegisterType((*Media)(nil), "io.cucumber.messages.Media")
	proto.RegisterType((*Source)(nil), "io.cucumber.messages.Source")
	proto.RegisterType((*SourceReference)(nil), "io.cucumber.messages.SourceReference")
}

func init() { proto.RegisterFile("sources.proto", fileDescriptor_sources_dbd726974e7b6608) }

var fileDescriptor_sources_dbd726974e7b6608 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x6b, 0x43, 0x3a, 0xb1, 0xa8, 0x8b, 0x48, 0x50, 0x28, 0x1a, 0x10, 0x3c, 0x05,
	0xac, 0xe0, 0x41, 0xf0, 0xa0, 0x82, 0x27, 0x7b, 0x59, 0x3d, 0x79, 0x29, 0xdb, 0xcd, 0x58, 0x17,
	0x92, 0xdd, 0x90, 0xec, 0x1e, 0xfa, 0x1a, 0x3e, 0xa6, 0x4f, 0x21, 0x99, 0x6c, 0x7a, 0x90, 0x1c,
	0x7b, 0x9b, 0x99, 0xfc, 0xf3, 0x7f, 0x3f, 0x99, 0x85, 0x59, 0x63, 0x5c, 0x2d, 0xb1, 0xc9, 0xaa,
	0xda, 0x58, 0xc3, 0x4e, 0x95, 0xc9, 0xa4, 0x93, 0xae, 0x5c, 0x63, 0x9d, 0x95, 0xd8, 0x34, 0x62,
	0x83, 0x4d, 0x7a, 0x0f, 0xd1, 0x9b, 0x91, 0xc2, 0x2a, 0xa3, 0x19, 0x83, 0x83, 0x42, 0x69, 0x4c,
	0x82, 0xcb, 0xe0, 0x66, 0xc6, 0xa9, 0x66, 0x67, 0x10, 0x4a, 0x53, 0xb8, 0x52, 0x27, 0x23, 0x9a,
	0xfa, 0x2e, 0xfd, 0x09, 0x00, 0x9e, 0xac, 0x15, 0xf2, 0xbb, 0x44, 0x6d, 0xd9, 0x23, 0x84, 0x1d,
	0x8d, 0x96, 0xe3, 0xc5, 0x75, 0x36, 0x44, 0xcb, 0xde, 0x49, 0xc3, 0xf1, 0x0b, 0x6b, 0xd4, 0x12,
	0xb9, 0x5f, 0x6a, 0xc9, 0xb9, 0xb0, 0x82, 0x18, 0x53, 0x4e, 0x35, 0xbb, 0x85, 0x49, 0x89, 0xb9,
	0x12, 0xc9, 0x98, 0x1c, 0x2f, 0x86, 0x1d, 0x97, 0xad, 0x84, 0x77, 0xca, 0xf4, 0x15, 0x26, 0xd4,
	0xb3, 0x73, 0x88, 0x50, 0x4b, 0x93, 0x2b, 0xbd, 0xa1, 0x40, 0x53, 0xbe, 0xeb, 0xd9, 0x15, 0x1c,
	0x4a, 0xa3, 0x2d, 0x6a, 0xbb, 0xb2, 0xdb, 0x0a, 0x3d, 0x33, 0xf6, 0xb3, 0x8f, 0x6d, 0x85, 0xa9,
	0x80, 0xb0, 0x4b, 0xca, 0x8e, 0x61, 0xec, 0x6a, 0xe5, 0x3d, 0xda, 0x72, 0x5f, 0x51, 0x57, 0x70,
	0xf4, 0xef, 0x67, 0x0c, 0xb0, 0x1e, 0x20, 0x2a, 0xfc, 0x71, 0x88, 0x17, 0x2f, 0xe6, 0xc3, 0xd6,
	0xfd, 0x09, 0xf9, 0x4e, 0xff, 0x3c, 0xff, 0x8c, 0xfa, 0xcf, 0xbf, 0xa3, 0x93, 0x97, 0x7e, 0x65,
	0xe9, 0x67, 0xeb, 0x90, 0x5e, 0xc5, 0xdd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x1c, 0xc4,
	0xd2, 0x26, 0x02, 0x00, 0x00,
}
