# frozen_string_literal: true
source 'https://rubygems.org'

gemspec

# TODO: Remove when https://github.com/ruby-protobuf/protobuf/pull/410 and
# https://github.com/ruby-protobuf/protobuf/pull/411 are merged and released
gem 'protobuf', git: 'https://github.com/cucumber/protobuf.git', branch: '3-10-cucumber'
