<?php

declare(strict_types=1);

/**
 * This code was generated by Berp (http://https://github.com/gasparnagy/berp/).
 *
 *  Changes to this file may cause incorrect behavior and will be lost if
 *  the code is regenerated.
 */

namespace Cucumber\Gherkin\Parser;

enum TokenType
{
    case None;
    case EOF;
    case Empty;
    case Comment;
    case TagLine;
    case FeatureLine;
    case RuleLine;
    case BackgroundLine;
    case ScenarioLine;
    case ExamplesLine;
    case StepLine;
    case DocStringSeparator;
    case TableRow;
    case Language;
    case Other;
}
