name: gherkin
description: Gherkin parser/compiler for Dart.
version: 0.0.1
homepage: https://github.com/lamkr/cucumber-common

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  #flutter:
  #  sdk: flutter
  #cupertino_icons: ^1.0.3

  characters: ^1.1.0
  uuid: ^3.0.4
  path: ^1.8.0

dev_dependencies:
  #flutter_test:
    #sdk: flutter
  pedantic: ^1.11.0
  test: ^1.17.4

flutter:
  assets:
    - assets/gherkin-languages.json

