# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pickles.proto

require 'google/protobuf'

require_relative 'sources_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "io.cucumber.messages.Pickle" do
    optional :uri, :string, 1
    optional :name, :string, 2
    optional :language, :string, 3
    repeated :steps, :message, 4, "io.cucumber.messages.PickleStep"
    repeated :tags, :message, 5, "io.cucumber.messages.PickleTag"
    repeated :locations, :message, 6, "io.cucumber.messages.Location"
  end
  add_message "io.cucumber.messages.PickleDocString" do
    optional :location, :message, 1, "io.cucumber.messages.Location"
    optional :contentType, :string, 2
    optional :content, :string, 3
  end
  add_message "io.cucumber.messages.PickleStep" do
    optional :text, :string, 1
    repeated :locations, :message, 2, "io.cucumber.messages.Location"
    oneof :argument do
      optional :doc_string, :message, 3, "io.cucumber.messages.PickleDocString"
      optional :data_table, :message, 4, "io.cucumber.messages.PickleTable"
    end
  end
  add_message "io.cucumber.messages.PickleTable" do
    repeated :rows, :message, 1, "io.cucumber.messages.PickleTableRow"
  end
  add_message "io.cucumber.messages.PickleTableCell" do
    optional :location, :message, 1, "io.cucumber.messages.Location"
    optional :value, :string, 2
  end
  add_message "io.cucumber.messages.PickleTableRow" do
    repeated :cells, :message, 1, "io.cucumber.messages.PickleTableCell"
  end
  add_message "io.cucumber.messages.PickleTag" do
    optional :location, :message, 1, "io.cucumber.messages.Location"
    optional :name, :string, 2
  end
end

module Cucumber
  module Messages
    Pickle = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.Pickle").msgclass
    PickleDocString = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.PickleDocString").msgclass
    PickleStep = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.PickleStep").msgclass
    PickleTable = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.PickleTable").msgclass
    PickleTableCell = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.PickleTableCell").msgclass
    PickleTableRow = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.PickleTableRow").msgclass
    PickleTag = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.PickleTag").msgclass
  end
end
