# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sources.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "io.cucumber.messages.Location" do
    optional :line, :uint32, 1
    optional :column, :uint32, 2
  end
  add_message "io.cucumber.messages.Attachment" do
    optional :source, :message, 1, "io.cucumber.messages.SourceReference"
    optional :data, :string, 2
    optional :media, :message, 3, "io.cucumber.messages.Media"
  end
  add_message "io.cucumber.messages.Media" do
    optional :encoding, :string, 1
    optional :content_type, :string, 2
  end
  add_message "io.cucumber.messages.Source" do
    optional :uri, :string, 1
    optional :data, :string, 2
    optional :media, :message, 3, "io.cucumber.messages.Media"
  end
  add_message "io.cucumber.messages.SourceReference" do
    optional :uri, :string, 1
    optional :location, :message, 2, "io.cucumber.messages.Location"
  end
end

module Cucumber
  module Messages
    Location = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.Location").msgclass
    Attachment = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.Attachment").msgclass
    Media = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.Media").msgclass
    Source = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.Source").msgclass
    SourceReference = Google::Protobuf::DescriptorPool.generated_pool.lookup("io.cucumber.messages.SourceReference").msgclass
  end
end
