source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

if ENV['USE_MONOREPO_GEM']
  gem 'cucumber-messages', path: "../../messages/ruby/"
end

gem 'rspec'
