#!/usr/bin/env bash
#
# Runs the formatter against a list of NDJSON files and writes the output
# next to each file
#

exitstatus=0

for ndjson in $*
do
  stdout="${ndjson}.json-formatter.json"
  stderr="${ndjson}.json-formatter.err.txt"
  output=$(./dist/cucumber-json-formatter-darwin-amd64 --format ndjson 2> "${stderr}" > "${stdout}" < ${ndjson})
done

exit ${exitstatus}