version: build{build}


environment:
  GherkinVersion: "4.0.1"
  GherkinPackageVersion: "$(GherkinVersion)-ci$(APPVEYOR_BUILD_NUMBER)"


nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Release


before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore dotnet\Gherkin.CSharp.sln
  
build:
  publish_nuget: true  

after_build:
  - set paddedVersion=000%APPVEYOR_BUILD_NUMBER%
  - set paddedVersion=%paddedVersion:~-3%
  - set GherkinPaddedPackageVersion=%GherkinVersion%-ci%paddedVersion%
  - nuget pack dotnet/Gherkin.NuGetPackages/Gherkin.nuspec -Version %GherkinPaddedPackageVersion%
  
artifacts:
- path: 'Gherkin.*.nupkg'
