#!/usr/bin/env bash
#
# Copies the toplevel LICENSE file to all the manyrepo directories
#
set -euf -o pipefail
source "$(dirname $0)/functions.sh"

travis_ymls | while read travis_yml; do
  manyrepo_dir=$(dirname ${travis_yml})
  echo "***** Building ${manyrepo_dir} *****"
  pushd "${manyrepo_dir}"
  make build
  popd
done
