#!/usr/bin/env bash
#
# Checks if you have enough karma to release libraries.
#
# Ok, it doesn't quite check that, but it runs some checks
# to see if you have at least authenticated with the various
# package managers that are likely to be used during a release.
#
set -euf -o pipefail
source "$(dirname $0)/functions.sh"

echo_green "Checking npm..."
npm whoami && echo_green "npm ok" || echo_red "\nYou need to: npm login"

echo_green "Checking rubygems..."
ls ~/.gem/credentials && echo_green "rubygems ok" || echo_red "\nYou need to: gem push"

echo_green "Checking maven..."
ls ~/.m2/settings.xml && echo_green "maven ok" || echo_red "\nFollow these instructions: https://maven.apache.org/guides/mini/guide-encryption.html"

echo_green "Checking gpg..."
ls ~/.gnupg/secring.gpg && echo_green "gpg ok" || echo_red "\nFollow these instructions: http://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/"
