#!/usr/bin/env bash
#
# This script runs at the beginning of the CI build. It sets up permissions
# so we can push to manyrepos.
#
# Inspiration: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#get-encrypted-credentials

set -euf -o pipefail

git config user.name "Cucumber CI"
git config user.email "cucumber-manyrepo@cucumber.io"

# travis env set CUCUMBER_MANYREPO_USER_TOKEN the-plain-text-token --private -r cucumber/cucumber
echo -e "machine github.com\n  login $CUCUMBER_MANYREPO_USER_TOKEN" >> ~/.netrc
