#!/usr/bin/env bash
#
# This script runs at the beginning of the CI build. It sets up permissions
# so we can push to manyrepos.
#
# Inspiration: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#get-encrypted-credentials

set -euf -o pipefail
source "$(dirname $0)/functions.sh"

git config user.name "Cucumber CI"
git config user.email "cucumber-manyrepo@cucumber.io"

# travis env set CUCUMBER_MANYREPO_USER_TOKEN the-plain-text-token --private -r cucumber/cucumber
echo -e "machine github.com\n  login $CUCUMBER_MANYREPO_USER_TOKEN" >> ~/.netrc

# ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
# ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
# ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
# ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}
# openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in cucumber_manyrepo_id_rsa.enc -out cucumber_manyrepo_id_rsa -d
#
# chmod 600 cucumber_manyrepo_id_rsa
# eval `ssh-agent -s`
# ssh-add cucumber_manyrepo_id_rsa
