#!/usr/bin/env bash
#
# Copies the toplevel LICENSE file to all the manyrepo directories
#
set -euf -o pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. ${DIR}/functions.sh

travis_ymls | while read travis_yml; do
  manyrepo_dir=$(dirname ${travis_yml})
  cp "${DIR}/../LICENSE" "${manyrepo_dir}"
done
