#!/usr/bin/env bash
#
# Runs the docker image
#
# Usage:
#   # Run `make` in the cucumber-build container
#   docker-run Dockerfile.cucumber-build make
#
#   # Run `make` in the cucumber-build-dotnet container
#   docker-run Dockerfile.cucumber-build-dotnet make
#
#   # Interactive bash session
#   docker-run Dockerfile.cucumber-build bash
#
set -ef -o pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LOCAL_PATH=$(pwd)

which wslpath
if [ $? -eq 0 ]
  then LOCAL_PATH="$(wslpath -w $(pwd))"
fi

source "${DIR}/functions.sh"
dockerfile=$1
shift
docker run \
  -e TRAVIS_BRANCH="${TRAVIS_BRANCH}" \
  -e TRAVIS_TAG="${TRAVIS_TAG}" \
  -v "${LOCAL_PATH}":/app \
  -it $(docker_image ${dockerfile}) $@
