#!/usr/bin/env bash
#
set -euf -o pipefail
source "$(dirname $0)/functions.sh"

manyrepos | while read manyrepo; do
  manyrepo_dir=$(cut -f1 <<< "${manyrepo}")
  manyrepo_name=$(cut -f2 <<< "${manyrepo}")

  echo "git subrepo init ${manyrepo_dir} -r https://github.com/${manyrepo_name}.git"
  git subrepo init ${manyrepo_dir} -r https://github.com/${manyrepo_name}.git
done
