#!/usr/bin/env bash
#
# Makes a github user a collaborator in every manyrepo, so that it can push
# to those, typically with the push_manyrepos script.
#
# In practice, the only github user we should add to the manyrepos is
# cucumber-manyrepo machine user.
# See (https://developer.github.com/guides/managing-deploy-keys/#machine-users)
# for an explanation.
#
# Before running this script (typically on a local computer) you need to
# define GITHUB_USERNAME=yourusername and GITHUB_ACCESS_TOKEN=... - you
# can create one at https://github.com/settings/tokens.
# Use public_repo and write:public_key scopes only.
#
# Usage: grant_push_manyrepos cucumber-manyrepo

set -euf -o pipefail
source "$(dirname $0)/functions.sh"

github_user=$1

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

travis_ymls | while read travis_yml; do
  manyrepo=$(awk '/^#[ \t]+manyrepo:/ {print $3}' ${travis_yml})

  echo -e "Making ${RED}${github_user}${NC} a push collaborator on ${GREEN}${manyrepo}${NC}"
  curl --user "${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN}" \
    --header "Content-Type: application/json" \
    --request PUT \
    --data '{"permission": "push"}' \
    https://api.github.com/repos/${manyrepo}/collaborators/${github_user}
done
