#!/usr/bin/env bash
#
# Installs splitsh-lite - a tool that splits a monorepo (this repo)
# into multiple manyrepos
#
# The build commands are copied from https://github.com/splitsh/lite#installation
#
set -euf -o pipefail

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}Installing libgit2${NC}"
go get -d github.com/libgit2/git2go
cd $GOPATH/src/github.com/libgit2/git2go
git checkout next
git submodule update --init
make install
cd -

echo -e "${GREEN}Installing splitsh-lite${NC}"
go get github.com/splitsh/lite
mkdir -p bin
go build -o bin/splitsh-lite github.com/splitsh/lite
