#!/usr/bin/env bash
#
# Releases all implementations of a particular library.
# For example:
#
#   ./scripts/release cucumber-expressions
#
# Before running this script you should make sure you are authenticated
# with all the various package managers
#
#   ./scripts/check-release-karma
#
set -euf -o pipefail
source "$(dirname $0)/functions.sh"

library=$1
cd "${library}"

manyrepos | while read manyrepo; do
  manyrepo_dir=$(cut -f1 <<< "${manyrepo}")
  manyrepo_name=$(cut -f2 <<< "${manyrepo}")
  release_dir="tmp/${manyrepo_dir}"
  rm -rf "${release_dir}"
  manyrepo_url=git@github.com:${manyrepo_name}.git
  echo_green "***** Cloning ${manyrepo_url} *****"
  git clone "${manyrepo_url}" "${release_dir}"
done
