# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'cucumber', '~> 4.1.0'  # Keep it at 4.1! json-to-messages aims to be used
                            # with cucumber which did not had messages
gem "rspec"
