= Standard Library

The Cucumber Standard Library is an effort to make Cucumber implementations
consistent across platforms.

This will benefit both users and contributors:
* The same Documentation can be used for all Cucumber implementations
* Moving between Cucumber implementations is a lot smoother
* Less duplicate effort for contributors (reusable components)
* It becomes easier to contribute to Cucumber (often just a matter of porting a library)
* Adding a new feature becomes easier because all implementations have a similar design

The table below shows the current libraries along with their implementation and
integration status. There are more planned libraries to come:

* Gherkin Parser
* Gherkin Compiler
* Data Tables
* Formatters
  * HTML
  * Pretty
  * JUnit

|===
|Platform |Cucumber Expressions |Tag Expressions

|.NET
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]

|Go
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]

|Java
|image:https://travis-ci.org/cucumber/cucumber-expressions-java.svg?branch=master["Build Status", link="https://travis-ci.org/cucumber/cucumber-expressions-java"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]
|image:https://travis-ci.org/cucumber/tag-expressions-java.svg?branch=master["Build Status", link="https://travis-ci.org/cucumber/tag-expressions-java"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]

|JavaScript
|image:https://travis-ci.org/cucumber/cucumber-expressions-javascript.svg?branch=master["Build Status", link="https://travis-ci.org/cucumber/cucumber-expressions-javascript"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]
|image:https://travis-ci.org/cucumber/tag-expressions-javascript.svg?branch=master["Build Status", link="https://travis-ci.org/cucumber/tag-expressions-javascript"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]

|Ojective-C
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]

|Perl
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]

|PHP
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]

|Python
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Build Status"]
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]

|Ruby
|image:https://travis-ci.org/cucumber/cucumber-expressions-ruby.svg?branch=master["Build Status", link="https://travis-ci.org/cucumber/cucumber-expressions-ruby"]
image:https://img.shields.io/badge/cucumber-%231002-red.svg["Integrated Into Cucumber", link="https://github.com/cucumber/cucumber-ruby/issues/1002"]
|image:https://img.shields.io/badge/build-not%20implemented-lightgrey.svg["Not Implemented", link="https://github.com/cucumber/cucumber/issues/60"] +
image:https://img.shields.io/badge/cucumber-not%20implemented-lightgrey.svg["Integrated Into Cucumber"]

|===
