# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "cucumber", git: 'https://github.com/cucumber/cucumber-ruby.git', branch: 'add-support-for-named-hooks'
gem "json"
gem "rspec"
